ALTER TYPE "FirmaModulTip" ADD VALUE IF NOT EXISTS 'HTML';
ALTER TYPE "FirmaModulTip" ADD VALUE IF NOT EXISTS 'TEK_GORSEL';
ALTER TYPE "FirmaModulTip" ADD VALUE IF NOT EXISTS 'SSS';
ALTER TYPE "FirmaModulTip" ADD VALUE IF NOT EXISTS 'HERO';
