-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "birimFiyat" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "indirim" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "kdvOrani" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "notlar" TEXT NOT NULL DEFAULT '';
